input {
  beats {
    port => 5044
  }
}

filter {
  # Only process SSH failed login messages
  if "Failed password" in [message] {

    grok {
      match => {
        "message" => "Failed password for %{WORD:user} from %{IP:source.ip}"
      }
    }

  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "filebeat-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}